DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
    SAMPLER: "RandomSampler"
    
  TEST:
    BATCH_SIZE: 32
    SAMPLER: "RandomSampler"
    
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)

OPTIM:
  NAME: "adadelta"
  LR: 0.15
  MAX_EPOCH: 50
  WEIGHT_DECAY: 1e-3
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 3
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-2

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  IMAGE_ADAPTER:
    REDUCTION: 4
    RATIO: 0.6
  
  TEXT_ADAPTER:
    REDUCTION: 4
    RATIO: 0.2

  ZSCLIP:
    PROMPT_TEMPLATE: "a photo of a {} - an industrial product."