DATASET:
  NAME: "ILID"
  MAX_NUM_WORDS: 5
  LABEL_TAG: "label_short"
  TEST_LABEL_TAG: "label_short"
  FOLDER: "ilid"

  SPLIT:
    NUM_SPLITS: 6
    SPLIT: 0

INPUT:
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.25, 0.25, 0.25]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]